#dependabot configuration

version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    cooldown:
      default-days: 1
    groups:
      react-deps:
        patterns:
          - "react"
          - "react-dom"
      tanstack-query:
        patterns:
          - "@tanstack*"
      lint:
        patterns:
          - "eslint*"
          - "@eslint*"
          - "globals"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"

